from flask import Flask, render_template

app = Flask(__name__)

LESSONS = [
{'id':'01','title':'How Flask works','group':'Foundations','time':'8 min','concept':'A Flask app connects URLs to Python functions. The browser sends an HTTP request, Flask finds the matching route, runs the function, and sends a response back.','syntax':"from flask import Flask\n\napp = Flask(__name__)\n\n@app.route('/')\ndef home():\n    return 'Hello, Flask!'",'why':'Flask creates an application object. The route decorator registers a URL rule. The function becomes the view that handles that URL. Its return value becomes the response.','remember':['A route is a URL-to-function mapping.','The decorator registers the route when the app is created.','The development server is for development, not production.'],'challenge':'Change the root route so it returns your name.'},
{'id':'02','title':'Routes and URL parameters','group':'Foundations','time':'8 min','concept':'Routes can capture values directly from the URL, allowing one function to serve many similar pages.','syntax':"@app.route('/user/<username>')\ndef user(username):\n    return f'Hello {username}'\n\n@app.route('/post/<int:post_id>')\ndef post(post_id):\n    return f'Post {post_id}'",'why':'A dynamic route value becomes a function argument. A converter such as int validates and converts the URL value before your function receives it.','remember':['Dynamic parts become function arguments.','Converters validate and convert values.','url_for() is safer than hard-coded URLs.'],'challenge':'Create /student/<int:id> and return the student ID.'},
{'id':'03','title':'GET, POST and request data','group':'Requests','time':'10 min','concept':'GET usually asks for data. POST usually sends data. Flask exposes incoming data through the request object.','syntax':"from flask import request\n\n@app.route('/search')\ndef search():\n    q = request.args.get('q', '')\n    return f'Searching for {q}'\n\n@app.route('/login', methods=['GET', 'POST'])\ndef login():\n    if request.method == 'POST':\n        username = request.form.get('username')\n        return f'Logged in as {username}'\n    return render_template('login.html')",'why':'request.args reads query-string data such as ?q=flask. request.form reads submitted form fields. methods tells Flask which HTTP methods the route accepts.','remember':['Query string -> request.args.','HTML form body -> request.form.','JSON body -> request.get_json().','Uploaded files -> request.files.'],'challenge':'Make a /hello endpoint that accepts ?name=Timothy.'},
{'id':'04','title':'Templates and Jinja','group':'Frontend','time':'12 min','concept':'Jinja lets Python send data into HTML without manually constructing HTML strings.','syntax':"from flask import render_template\n\n@app.route('/dashboard')\ndef dashboard():\n    products = ['Piano', 'Guitar', 'Drums']\n    return render_template('dashboard.html', products=products)",'why':'render_template looks inside the templates folder and renders the selected file. Keyword arguments become template variables.','remember':['{{ value }} prints a value.','{% if %} and {% for %} control logic.','Jinja auto-escapes normal HTML templates.'],'challenge':'Pass a name variable into a template and display it.'},
{'id':'05','title':'Jinja control flow and inheritance','group':'Frontend','time':'10 min','concept':'Real applications reuse a base layout instead of duplicating navigation, scripts and page structure.','syntax':"<!-- base.html -->\n{% block content %}{% endblock %}\n\n<!-- dashboard.html -->\n{% extends 'base.html' %}\n{% block content %}\n  <h1>Dashboard</h1>\n  {% for item in items %}<p>{{ item }}</p>{% endfor %}\n{% endblock %}",'why':'extends reuses the base template. block defines replaceable regions. This keeps pages consistent and reduces duplicated HTML.','remember':['Use Jinja statements inside {% ... %}.','Use {{ ... }} for displayed expressions.','Filters can transform values such as title.'],'challenge':'Create a base layout with a navbar and a content block.'},
{'id':'06','title':'Redirects, url_for and flash','group':'Navigation','time':'8 min','concept':'After processing a form, redirect the browser to another route. Flash messages provide short-lived feedback.','syntax':"from flask import redirect, url_for, flash\n\nflash('Saved successfully!', 'success')\nreturn redirect(url_for('dashboard'))",'why':'url_for generates the URL from the endpoint name, so route changes are easier to manage. Redirecting after POST prevents accidental duplicate submissions on refresh.','remember':['url_for uses the endpoint name.','The default endpoint is the view function name.','Flash messages are intended for the next request.'],'challenge':'After a successful form submission, redirect to dashboard and show a success message.'},
{'id':'07','title':'Static files','group':'Frontend','time':'6 min','concept':'CSS, JavaScript, images and fonts belong in the static folder and are referenced with Flask static URLs.','syntax':"<link rel='stylesheet' href=\"{{ url_for('static', filename='css/style.css') }}\">\n<script src=\"{{ url_for('static', filename='js/app.js') }}\"></script>",'why':'Flask knows where its static directory is. url_for creates the correct asset URL without hard-coding paths.','remember':['Keep templates and static assets separate.','Use url_for for generated URLs.','A production web server can serve static files efficiently.'],'challenge':'Add a CSS file and use it to style your first Flask page.'},
{'id':'08','title':'Sessions and authentication basics','group':'Users','time':'12 min','concept':'Sessions let a browser carry signed state between requests. Authentication combines sessions with password verification and authorization.','syntax':"from flask import session\n\napp.config['SECRET_KEY'] = 'use-a-real-secret-in-production'\nsession['user_id'] = user.id\nuser_id = session.get('user_id')\nsession.clear()",'why':'Flask signs session data so it cannot be silently changed without invalidating the signature. The secret key is security-sensitive and belongs in environment configuration.','remember':['Session state is not a database replacement.','Never store passwords in sessions.','Authentication asks who you are; authorization asks what you may do.'],'challenge':'Create login and logout routes that store and remove a user ID.'},
{'id':'09','title':'Passwords and access control','group':'Users','time':'10 min','concept':'Passwords must be hashed, never stored as plain text. Protected routes must verify both identity and permissions.','syntax':"from werkzeug.security import generate_password_hash, check_password_hash\n\nhashed = generate_password_hash(password)\ncheck_password_hash(hashed, password)\n\nif not user or user.role != 'admin':\n    abort(403)",'why':'Hashing creates a one-way representation suitable for storage. Verification compares the supplied password safely. Role checks enforce authorization.','remember':['Never store plaintext passwords.','403 means access is forbidden.','Authorization must be checked on the server.'],'challenge':'Add an admin role and protect one route with a server-side role check.'},
{'id':'10','title':'SQL and database thinking','group':'Database','time':'12 min','concept':'A database stores structured data. Before the ORM, understand tables, rows, keys and basic SQL.','syntax':"SELECT * FROM users;\nSELECT * FROM users WHERE id = 5;\nINSERT INTO users (name) VALUES ('Timothy');\nUPDATE users SET name = 'Timo' WHERE id = 5;\nDELETE FROM users WHERE id = 5;",'why':'SQL describes the data operation. Primary keys identify records. Foreign keys connect records between tables.','remember':['Table = collection of records.','Row = one record.','Column = one attribute.','Primary key uniquely identifies a row.','Foreign key connects tables.'],'challenge':'Design tables for users, products and orders before writing Flask code.'},
{'id':'11','title':'Flask-SQLAlchemy models','group':'Database','time':'12 min','concept':'An ORM lets Python classes represent database tables and objects represent rows.','syntax':"from flask_sqlalchemy import SQLAlchemy\n\ndb = SQLAlchemy()\n\nclass Product(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    name = db.Column(db.String(120), nullable=False)\n    price = db.Column(db.Float, nullable=False)",'why':'The model class describes the table. Columns describe stored fields. SQLAlchemy translates Python operations into SQL and manages database sessions.','remember':['Model class -> table.','Model instance -> row.','Column definition -> database column.','Use migrations when schema changes.'],'challenge':'Create a Student model with an ID, name and class.'},
{'id':'12','title':'CRUD with SQLAlchemy','group':'Database','time':'12 min','concept':'CRUD means Create, Read, Update and Delete, the core operations behind most database-backed applications.','syntax':"product = Product(name='Keyboard', price=50000)\ndb.session.add(product)\ndb.session.commit()\n\nproducts = Product.query.all()\nproduct = db.session.get(Product, 1)\nproduct.price = 55000\ndb.session.commit()\ndb.session.delete(product)\ndb.session.commit()",'why':'db.session tracks changes. commit persists them. Queries return model objects that you can use like normal Python objects.','remember':['Add then commit to create.','Query to read.','Change attributes then commit to update.','Delete then commit to remove.'],'challenge':'Build a product CRUD page with create, list, edit and delete actions.'},
{'id':'13','title':'Queries and filtering','group':'Database','time':'10 min','concept':'Most real apps need more than all(). Learn to filter, sort, limit and retrieve safely.','syntax':"Product.query.filter_by(name='Keyboard').first()\nProduct.query.filter(Product.price > 10000).all()\nProduct.query.order_by(Product.price.desc()).all()\nProduct.query.limit(10).all()",'why':'Query methods build a database query. Retrieval methods execute it and return model objects. Filtering in the database avoids loading unnecessary data into Python.','remember':['first returns one result or None.','all returns a list.','Validate user-controlled IDs and filters.'],'challenge':'Make a product search endpoint that filters by a search term.'},
{'id':'14','title':'Relationships','group':'Database','time':'12 min','concept':'Relationships model connections such as one user having many orders or students taking many subjects.','syntax':"class User(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    orders = db.relationship('Order', backref='user', lazy=True)\n\nclass Order(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)",'why':'The foreign key stores the database connection. relationship gives Python a convenient way to navigate related objects.','remember':['Foreign keys enforce database links.','One-to-many is extremely common.','Many-to-many usually needs an association table.'],'challenge':'Model Teacher to Students and explain where the foreign key belongs.'},
{'id':'15','title':'File uploads','group':'Web Features','time':'10 min','concept':'Forms can upload files when the request uses multipart encoding. Flask exposes them through request.files.','syntax':"<form method='post' enctype='multipart/form-data'>\n  <input type='file' name='image'>\n  <button>Upload</button>\n</form>\n\nfile = request.files.get('image')\nif file and file.filename:\n    file.save(path)",'why':'The browser uses multipart encoding for binary files. The server must validate type, size and filename before saving anything.','remember':['Use multipart/form-data.','Never trust the original filename.','Use secure_filename and server-side validation.','Do not allow arbitrary executable uploads.'],'challenge':'Add an avatar upload to a profile page.'},
{'id':'16','title':'Blueprints','group':'Architecture','time':'10 min','concept':'Blueprints split a large Flask application into logical modules such as auth, admin and products.','syntax':"from flask import Blueprint\n\nauth = Blueprint('auth', __name__, url_prefix='/auth')\n\n@auth.route('/login')\ndef login():\n    ...\n\napp.register_blueprint(auth)",'why':'A blueprint records routes and related behavior before being registered on the application. This prevents one giant app.py file as your project grows.','remember':['Blueprints are not separate Flask applications.','Register each blueprint with the app.','Blueprint endpoint names include the blueprint name.'],'challenge':'Move login and logout into an auth blueprint.'},
{'id':'17','title':'Application factory and configuration','group':'Architecture','time':'12 min','concept':'An application factory creates the Flask app inside a function, making configuration, testing and multiple app instances easier.','syntax':"def create_app():\n    app = Flask(__name__)\n    app.config.from_mapping(SECRET_KEY='dev')\n    db.init_app(app)\n    app.register_blueprint(auth)\n    return app",'why':'Creating the app inside a function avoids global initialization and gives tests or different environments a controlled way to create configured instances.','remember':['Factory creates and configures the app.','Extensions can use init_app(app).','Keep secrets and environment-specific settings outside source code.'],'challenge':'Refactor a one-file Flask app into create_app().' },
{'id':'18','title':'JSON APIs','group':'APIs','time':'10 min','concept':'Flask can serve JSON so browsers, mobile apps and other services can communicate with your backend.','syntax':"from flask import jsonify, request\n\n@app.get('/api/products')\ndef products():\n    return jsonify([{'id': 1, 'name': 'Keyboard'}])\n\n@app.post('/api/products')\ndef create_product():\n    data = request.get_json()\n    return jsonify({'received': data}), 201",'why':'jsonify creates a JSON response with the correct content type. get_json parses a JSON request body.','remember':['Use meaningful HTTP status codes.','Validate incoming JSON.','Do not expose database objects or secrets blindly.'],'challenge':'Create GET and POST endpoints for a notes resource.'},
{'id':'19','title':'JavaScript fetch and Flask','group':'APIs','time':'10 min','concept':'Fetch lets the browser call Flask without a full page reload, enabling interactive search, carts and dashboards.','syntax':"const response = await fetch('/api/products');\nconst products = await response.json();\n\nawait fetch('/api/products', {\n  method: 'POST',\n  headers: {'Content-Type': 'application/json'},\n  body: JSON.stringify({name: 'Piano'})\n});",'why':'JavaScript sends an HTTP request to Flask. Flask returns JSON. JavaScript updates the page. The backend remains responsible for validation and authorization.','remember':['Fetch does not remove server-side validation.','Handle non-2xx responses.','Parse JSON before using it as an object.'],'challenge':'Build a search box that calls Flask and renders results without reloading.'},
{'id':'20','title':'Errors, status codes and debugging','group':'Reliability','time':'10 min','concept':'Good Flask apps fail predictably and show useful messages while keeping sensitive details out of production responses.','syntax':"from flask import abort\n\nabort(404)\n\n@app.errorhandler(404)\ndef not_found(error):\n    return render_template('404.html'), 404",'why':'HTTP status codes communicate what happened. Error handlers turn failures into controlled responses. Debug mode is useful locally but must not be exposed in production.','remember':['400 = bad request.','401 = authentication required.','403 = forbidden.','404 = not found.','500 = server error.'],'challenge':'Create custom 404 and 500 pages.'},
{'id':'21','title':'Security essentials','group':'Security','time':'14 min','concept':'Security is part of Flask development, not an afterthought. Protect input, authentication, sessions, uploads and secrets.','syntax':"app.config['SECRET_KEY'] = os.environ['SECRET_KEY']\n\n# Validate input before using it\n# Hash passwords\n# Use parameterized ORM queries\n# Enable CSRF protection for browser forms\n# Never expose debug mode in production",'why':'Attackers control client input. Your server must assume every request can be malicious. Framework defaults help, but application-level authorization and validation remain your responsibility.','remember':['XSS -> escape untrusted HTML.','CSRF -> protect state-changing browser forms.','SQL injection -> parameterized queries or ORM.','Broken authorization -> check permissions server-side.','Secrets -> environment variables.'],'challenge':'Review a login route and list three security checks it needs.'},
{'id':'22','title':'Environment variables','group':'Deployment','time':'6 min','concept':'Configuration that changes between machines or contains secrets should not be hard-coded into your repository.','syntax':"import os\n\nSECRET_KEY = os.getenv('SECRET_KEY')\nDATABASE_URL = os.getenv('DATABASE_URL')",'why':'Development, testing and production need different settings. Environment variables let the deployment platform provide values without putting secrets in Git.','remember':['Never commit production passwords or API keys.','Fail clearly when required configuration is missing.','Use a local .env only when it is ignored by Git.'],'challenge':'Move your Flask secret key out of source code.'},
{'id':'23','title':'Migrations','group':'Database','time':'8 min','concept':'When models change, migrations safely describe how the existing database schema should change.','syntax':"flask db init\nflask db migrate -m 'add product image'\nflask db upgrade",'why':'Your Python model and deployed database are separate things. A migration records the schema change so it can be applied consistently instead of deleting the database.','remember':['Do not casually delete production databases to change a model.','Review generated migrations.','Commit migrations to Git.'],'challenge':'Add a field to a model and describe the migration you would create.'},
{'id':'24','title':'Testing Flask applications','group':'Reliability','time':'10 min','concept':'Tests send requests to your Flask app and verify routes, permissions and data behavior remain correct as the project grows.','syntax':"def test_home(client):\n    response = client.get('/')\n    assert response.status_code == 200\n\nresponse = client.post('/login', data={'username': 'admin'})",'why':'A test is a repeatable check. When code changes, tests tell you whether existing behavior still works.','remember':['Test important user flows.','Test success and failure cases.','Authentication and authorization deserve dedicated tests.'],'challenge':'Write tests for login success, login failure and forbidden admin access.'},
{'id':'25','title':'Deployment and production','group':'Deployment','time':'12 min','concept':'A production Flask deployment normally places a production WSGI server between the internet and your Flask application.','syntax':"gunicorn 'app:create_app()'\n\n# Typical flow:\n# Browser -> HTTPS -> platform/proxy -> Gunicorn -> Flask -> database",'why':'Flask development server is designed for development. A production server such as Gunicorn handles application processes appropriately for deployment platforms.','remember':['Disable debug mode in production.','Use environment variables.','Use a production database such as PostgreSQL when appropriate.','Read deployment logs when debugging.'],'challenge':'Explain the difference between flask run and Gunicorn in your own words.'},
{'id':'26','title':'Advanced Flask map','group':'Next Level','time':'10 min','concept':'Once the core is solid, Flask also provides contexts, CLI commands, class-based views, async support, middleware, signals and more.','syntax':"@app.cli.command('seed')\ndef seed():\n    # custom Flask CLI command\n    ...\n\n@app.before_request\ndef before_request():\n    ...",'why':'These features solve specialized problems. You do not need to memorize them now; recognize when the problem calls for them and know where to look.','remember':['Application context powers current_app and extension access.','Request context powers request and session.','Use advanced features when they solve a real architectural need.'],'challenge':'Pick one advanced feature and explain a project where it would be useful.'}
]

QUIZZES = [
('What connects a URL to a Python function?',['A model','A route','A session','A migration'],1),
('Where does ?q=flask appear in Flask?',['request.form','request.files','request.args','session'],2),
('What does render_template primarily do?',['Creates a database','Renders a Jinja template','Starts the server','Hashes a password'],1),
('Why use url_for?',['To hash URLs','To generate URLs from endpoints','To create database URLs only','To upload files'],1),
('Which object stores Flask session data?',['session','request.args','db.session','g only'],0),
('What should be stored instead of a plaintext password?',['A reversible encrypted password','A password hash','The session ID','The username twice'],1),
('What does db.session.commit do?',['Starts Flask','Persists pending database changes','Creates a route','Clears browser cookies'],1),
('What is a foreign key for?',['Styling forms','Connecting records between tables','Hashing passwords','Serving CSS'],1),
('What is a Blueprint mainly for?',['Database backups','Modularizing Flask applications','Replacing HTML','Encrypting sessions'],1),
('What does request.get_json read?',['A JSON request body','A CSS file','A database migration','A session cookie only'],0),
('Which status code means Forbidden?',['200','301','403','500'],2),
('Where should production secrets normally come from?',['GitHub README','Environment variables or secret configuration','HTML comments','A public JSON file'],1),
('Why are migrations used?',['To change database schema safely','To make CSS faster','To log users in','To replace Flask'],0),
('What should you use instead of Flask development server for production?',['A production WSGI server such as Gunicorn','Debug mode','Python REPL','Jinja only'],0)
]

@app.get('/')
def home():
    quizzes=[{'q':q,'options':o,'answer':a} for q,o,a in QUIZZES]
    return render_template('index.html', lessons=LESSONS, quizzes=quizzes)

if __name__ == '__main__':
    app.run(debug=True)
